[project]
name = "sakila-lab-alicia-gezelius"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[sql-database]>=1.19.0",
    "duckdb>=1.4.2",
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
]
